// app/corpora/debates/index.js
// Parliamentary debates — speech-level (LS) and daily-proceedings (RS, phase B).
//
// Phase A: Lok Sabha only. The architecture (house-keyed reports,
// house-stratified text/, generic house filter in the UI) is designed
// so Rajya Sabha lands additively when phase B ships.
//
// Source: sansad.in's api_ls/debate/* endpoints. Daily-mirrored via
// parliamentwatch-data's build_debates.py + debates.yml.
//
// Macro group: `proceedings` — a new group introduced with this corpus.
// Questions (slot 7) will join this group later.
//
// Independence Principle: this file does not import from cag, lc, fc,
// drsc, or bills corpus modules. Composite reportKey shape
// `debates|ls|<lok_sabha>|<session>|<dbSlno>` (and later
// `debates|rs|<session>|<date>`).
//
// Storage strategy: no PDFs in LS phase. The mirror's text/ contains
// the plain-text body (HTML-stripped from upstream). No "Archive copy"
// link in the detail panel — there's no PDF to archive.

import {
  idbGet, idbPut, idbCursor,
  escapeHtml, debounce,
  loadSettings, saveSettings,
  formatLocalTimestamp,
  mapPooled,
} from '../../deps.js';
import { streamWithPersistence } from '../../ai-streaming.js';
import {
  parseQuery, highlightMatches,
} from '../../corpus-search.js';
import { hydrateFromIDB } from '../../corpus-data.js';
import { loadTextFromShards } from '../../text-shards.js';

const CORPUS_PREFIX = 'debates/';

// ── Constants ───────────────────────────────────────────────────────────────

const HOUSES = {
  ls: { short: 'LS', long: 'Lok Sabha' },
  rs: { short: 'RS', long: 'Rajya Sabha' },   // populated when phase B ships
};

const HOUSE_PILL_CLASS = {
  ls: 'L',   // orange (existing house-L styling)
  rs: 'R',   // navy   (existing house-R styling)
};

const SUMMARY_PROMPT = `You are summarising a parliamentary debate intervention from the Indian Lok Sabha. The text below is a single floor intervention (a speech, ruling, statement, special mention, or procedural item). Produce a clear, plain-English briefing for a busy reader.

Use this structure:

1. **What this is** (1 sentence — type of intervention, who spoke, when)
2. **What was said** (3-6 bullets — the substantive points raised. If procedural, describe what was done.)
3. **Context** (1-2 sentences — what bill/issue/event this was about, if discernible)
4. **Why it matters** (1 sentence — political / policy / procedural significance, if any)

Keep it neutral, factual, and accessible to a non-specialist. Do not invent claims or context not in the text.

DEBATE:
{TEXT}`;

function buildAskPrompt({ summary, text, searchResults, question }) {
  const parts = [
    'You are answering questions about a specific parliamentary debate intervention from the Indian Lok Sabha. Use only the supplied material below. If the answer isn\'t in the supplied material, say so clearly.',
  ];
  if (summary) parts.push('', 'SUMMARY (previously generated by AI):', summary);
  parts.push('', 'DEBATE:', text);
  if (searchResults && searchResults.length) {
    parts.push('', 'RECENT WEB CONTEXT (use cautiously, prefer the debate itself when they conflict):');
    for (const r of searchResults) parts.push(`- ${r.title}\n  ${r.url}\n  ${r.snippet}`);
  }
  parts.push('', '---', '', 'QUESTION: ' + question);
  return parts.join('\n');
}

// ── Module-private state ────────────────────────────────────────────────────

const state = {
  // reports is house-keyed: {ls: [...], rs: [...]}
  data: { reports: {}, manifest: {}, meta: null },
  filtered: [],
  selectedReport: null,
  filters: {
    search: '', house: '', lok_sabha: '', session: '',
    debate_type: '', year: '', sort: 'newest',
  },

  cache: {
    summaries: {},
    text:      {},
    chats:     {},
  },

  dialogChat: [],

  // RS only — which version is showing in the Full text tab. Defaults
  // to 'floor' (canonical) but the user can switch via the picker.
  // Reset on each report-open.
  rsSelectedVersion: 'floor',

  streamingContext: null,
};

let _deps = null;
let _activated = false;

// ── Helpers ─────────────────────────────────────────────────────────────────

function reportKey(r) {
  if (r.house === 'ls') return `debates|ls|${r.lok_sabha}|${r.session}|${r.db_slno}`;
  // RS uses ISO date (yyyy-mm-dd) for stable sortability.
  if (r.house === 'rs') return `debates|rs|${r.session}|${r.date_iso || r.date}`;
  return `debates|?|${r.lok_sabha || '?'}|${r.session || '?'}|${r.db_slno || r.date || '?'}`;
}

// LS records have one file_id. RS records have multiple (one per version
// in file_versions). `fileId(r, version='floor')` returns the per-version
// id for RS; for LS the version arg is ignored.
function fileId(r, version = 'floor') {
  if (r.house === 'ls') return `LS${r.lok_sabha}_S${r.session}_${r.db_slno}`;
  if (r.house === 'rs') {
    const iso = r.date_iso || (r.date || '').split('/').reverse().join('-');
    return `RS${r.session}_${iso}_${version}`;
  }
  return '';
}

// RS-only: which versions are actually extracted and available?
function rsAvailableVersions(r) {
  if (r.house !== 'rs') return [];
  const byVer = state.data.manifest?.texts?.rs?.[`RS${r.session}_${r.date_iso || (r.date || '').split('/').reverse().join('-')}`] || {};
  // Order: floor → english → part1 (canonical, then EN translation, then Q&A subset)
  return ['floor', 'english', 'part1'].filter(v => byVer[v]);
}

function parseDate(s) {
  if (!s) return null;
  // sansad.in dates are DD/MM/YYYY
  const m = String(s).match(/^(\d{1,2})\/(\d{1,2})\/(\d{4})$/);
  if (m) {
    const d = new Date(`${m[3]}-${m[2]}-${m[1]}`);
    if (!isNaN(d)) return d;
  }
  const d2 = new Date(s);
  if (!isNaN(d2)) return d2;
  return null;
}

function reportDate(r) {
  if (r.house === 'ls') return parseDate(r.debate_date);
  if (r.house === 'rs') return parseDate(r.date);
  return null;
}

function reportYear(r) {
  const d = reportDate(r);
  return d ? d.getFullYear() : null;
}

function memberLine(r) {
  if (r.house !== 'ls') return '';
  const ms = r.members || [];
  if (!ms.length) return '';
  if (ms.length === 1) return ms[0].mp_name || '';
  if (ms.length === 2) return `${ms[0].mp_name}, ${ms[1].mp_name}`;
  return `${ms[0].mp_name} + ${ms.length - 1} others`;
}

// ── Data fetching ───────────────────────────────────────────────────────────

// Fetch the debates record metadata, transparently handling both the new
// sharded shape (reports-meta.json + reports-<house>-<NN>.json) and the
// legacy single-file shape (reports.json). The sharded shape is required
// because debates' merged record list crossed Cloudflare's 25 MiB per-file
// cap during the LS-14..18 walk; the single file can't be deployed anymore.
// Fallback is retained so the app still works against an older data-repo
// snapshot during the brief window between app deploy and data-repo deploy.
//
// Returns the canonical `{ls: [...], rs: [...]}` shape regardless of source.
async function fetchReports(dataUrl, v, fetchOpts) {
  // Prefer sharded format. A 404 here is the cue to fall back; any other
  // failure (network, JSON parse) is also treated as fall-back-worthy
  // rather than fatal, so a transient blip on reports-meta doesn't break
  // the load when reports.json is still around.
  // Fall back to the legacy single file ONLY when reports-meta.json is
  // genuinely absent (404). The previous shape caught *any* error from the
  // sharded path — including a transient failure on one shard out of
  // hundreds — and fell through to reports.json, which has not existed since
  // sharding landed on 2026-05-14. So every sharded-path hiccup surfaced as
  // `reports.json: 404`, pointing at a file that is supposed to be missing.
  // That is exactly what masked the real cause during the 2026-07-27 outage:
  // the actual error was a connection-pool rejection on the shard fetches.
  const metaResp = await fetch(dataUrl + CORPUS_PREFIX + 'reports-meta.json' + v, fetchOpts);
  if (metaResp.status !== 404) {
    if (!metaResp.ok) throw new Error(`reports-meta.json: ${metaResp.status}`);
    {
      const reportsMeta = await metaResp.json();
      const shardsByHouse = reportsMeta?.shards || {};
      const merged = {};
      const tasks = [];
      for (const [house, entries] of Object.entries(shardsByHouse)) {
        merged[house] = [];
        // Order comes from the manifest's entry order, NOT from an index in
        // the shard payload — see app/corpora/questions/index.js.
        entries.forEach((entry, i) => {
          tasks.push({ house, idx: i, file: entry.file });
        });
      }
      // Bounded pool — bucket-named shards mean ~1.8k reports files here, and
      // firing them all at once fails the whole load with "Failed to fetch",
      // which this function then silently swallows into the legacy
      // reports.json fallback (a 404 since the 2026-05-14 sharding).
      const shardResults = await mapPooled(tasks, async t => {
        const r = await fetch(dataUrl + CORPUS_PREFIX + t.file + v, fetchOpts);
        if (!r.ok) throw new Error(`${t.file}: ${r.status}`);
        const payload = await r.json();
        return { house: t.house, idx: t.idx, records: payload?.records || [] };
      });
      // Sort defensively by (house, shard_index) so concat order is
      // deterministic even if shard_index is missing on legacy entries.
      shardResults.sort((a, b) =>
        a.house === b.house ? a.idx - b.idx : a.house.localeCompare(b.house));
      for (const { house, records } of shardResults) {
        merged[house].push(...records);
      }
      return merged;
    }
  }

  // Legacy single-file fallback — reached only when reports-meta.json is a
  // genuine 404, i.e. an old data-repo snapshot from before sharding.
  const resp = await fetch(dataUrl + CORPUS_PREFIX + 'reports.json' + v, fetchOpts);
  if (!resp.ok) throw new Error(`reports.json: ${resp.status}`);
  return resp.json();
}

async function fetchData(forceRefresh = false) {
  const splash    = document.getElementById('splash');
  const dataUrl   = _deps.config.dataBaseUrl;

  if (!forceRefresh) {
    try {
      const [reportsBlob, manifestBlob, metaBlob] = await Promise.all([
        idbGet('blobs', 'debates-reports.json'),
        idbGet('blobs', 'debates-manifest.json'),
        idbGet('blobs', 'debates-meta.json'),
      ]);
      if (reportsBlob && manifestBlob) {
        state.data.reports  = reportsBlob;
        state.data.manifest = manifestBlob;
        state.data.meta     = metaBlob || null;
      }
    } catch (e) { console.warn('debates IDB cache miss', e); }
  }

  const haveCache = Object.values(state.data.reports).some(v => Array.isArray(v) && v.length);
  const bucket = Math.floor(Date.now() / 300000);
  const v = forceRefresh ? `?v=${Date.now()}` : `?v=${bucket}`;
  const fetchOpts = { cache: 'no-cache' };

  try {
    const [reports, manifest, meta] = await Promise.all([
      fetchReports(dataUrl, v, fetchOpts),
      fetch(dataUrl + CORPUS_PREFIX + 'manifest.json' + v, fetchOpts).then(r => r.ok ? r.json() : { texts: {} }).catch(() => ({ texts: {} })),
      fetch(dataUrl + CORPUS_PREFIX + 'meta.json'     + v, fetchOpts).then(r => r.ok ? r.json() : null).catch(() => null),
    ]);
    state.data.reports  = reports;
    state.data.manifest = manifest;
    state.data.meta     = meta;

    idbPut('blobs', 'debates-reports.json',  reports).catch(() => {});
    idbPut('blobs', 'debates-manifest.json', manifest).catch(() => {});
    if (meta) idbPut('blobs', 'debates-meta.json', meta).catch(() => {});
  } catch (err) {
    console.error('debates fetch failed', err);
    if (!haveCache) {
      _deps.ui.toast('Could not fetch debates data — see console for details');
      return false;
    }
    _deps.ui.toast('Debates offline — using cached data');
  }

  splash?.classList.add('hide');
  return true;
}

// RS records have multi-version text. `version` is 'floor' (default),
// 'english', or 'part1' — ignored for LS. Cache key is per-version so
// switching versions on the same record doesn't smash cache.
async function fetchReportText(report, version = 'floor') {
  const baseKey = reportKey(report);
  // LS: single body. RS: one cache entry per version.
  const cacheKey = report.house === 'rs' ? `${baseKey}#${version}` : baseKey;
  if (state.cache.text[cacheKey]) return state.cache.text[cacheKey];

  try {
    const cached = await idbGet('texts', cacheKey);
    if (cached) {
      state.cache.text[cacheKey] = cached;
      return cached;
    }
  } catch {}

  // Resolve the manifest entry. For LS, manifest.texts.ls[<file_id>] is
  // a flat {size,url}. For RS, manifest.texts.rs[<base_id>] is a dict
  // keyed by version: {floor:{size,url}, english:{...}, part1:{...}}.
  let entry;
  let compositeKey;
  if (report.house === 'ls') {
    const fid = fileId(report);
    entry = state.data.manifest?.texts?.ls?.[fid];
    compositeKey = `ls|${fid}`;
  } else if (report.house === 'rs') {
    const base = fileId(report, 'floor').replace(/_floor$/, '');
    entry = state.data.manifest?.texts?.rs?.[base]?.[version];
    compositeKey = `rs|${base}|${version}`;
  }
  if (!entry) return null;

  // Primary path: bundled text-shards.
  if (compositeKey) {
    try {
      const text = await loadTextFromShards('debates', compositeKey, _deps.config.dataBaseUrl);
      if (text !== null) {
        state.cache.text[cacheKey] = text;
        idbPut('texts', cacheKey, text).catch(() => {});
        _deps.disk?.write?.('debates', entry.url, text).catch(() => {});
        return text;
      }
    } catch (e) {
      console.warn('debates: text-shard fetch failed, falling back to legacy URL', e);
    }
  }

  // Legacy fallback: per-file text/{ls,rs}/<...>.txt.
  try {
    const res = await fetch(_deps.config.dataBaseUrl + CORPUS_PREFIX + entry.url);
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    const text = await res.text();
    state.cache.text[cacheKey] = text;
    idbPut('texts', cacheKey, text).catch(() => {});
    _deps.disk?.write?.('debates', entry.url, text).catch(() => {});
    return text;
  } catch (e) {
    try {
      const fromDisk = await _deps.disk?.read?.('debates', entry.url);
      if (fromDisk) {
        state.cache.text[cacheKey] = fromDisk;
        idbPut('texts', cacheKey, fromDisk).catch(() => {});
        return fromDisk;
      }
    } catch {}
    console.warn('debates: failed to fetch text', e);
    return null;
  }
}

// ── Filtering / list rendering ──────────────────────────────────────────────

function getAllReports() {
  const out = [];
  for (const h of Object.keys(HOUSES)) {
    for (const r of (state.data.reports[h] || [])) {
      out.push({ ...r, house: h, _date: reportDate(r), _year: reportYear(r) });
    }
  }
  return out;
}

function applyFilters() {
  const all = getAllReports();
  const f = state.filters;
  const rawQ = f.search.trim();
  const parsedQ = rawQ ? parseQuery(rawQ) : null;

  const filtered = all.filter(r => {
    if (f.house && r.house !== f.house) return false;
    if (f.lok_sabha && (r.house !== 'ls' || String(r.lok_sabha) !== f.lok_sabha)) return false;
    if (f.session && String(r.session) !== f.session) return false;
    if (f.debate_type && (r.house !== 'ls' || String(r.debate_type) !== f.debate_type)) return false;
    if (f.year && String(r._year || '') !== f.year) return false;
    if (!parsedQ) return true;

    const titleLower = (r.title || '').toLowerCase();
    const tokenHits = (tok) => titleLower.includes(tok);
    const phraseHits = (phrase) => titleLower.includes(phrase);
    return parsedQ.tokens.every(tokenHits)
        && parsedQ.phrases.every(phraseHits);
  });

  filtered.sort((a, b) => {
    switch (f.sort) {
      case 'oldest':  return (a._date || 0) - (b._date || 0);
      case 'house':   return (a.house || '').localeCompare(b.house || '')
                          || ((b._date || 0) - (a._date || 0));
      case 'type':    return (a.debate_type_desc || '').localeCompare(b.debate_type_desc || '')
                          || ((b._date || 0) - (a._date || 0));
      case 'newest':
      default:        return (b._date || 0) - (a._date || 0)
                          || ((b.db_slno || 0) - (a.db_slno || 0));
    }
  });

  state.filtered = filtered;
  renderList();
  renderResultsLine();
}

function renderResultsLine() {
  const el = document.getElementById('resultsLine');
  if (!el) return;
  const total = getAllReports().length;
  const shown = state.filtered.length;
  el.innerHTML = (shown > 0 && shown < total)
    ? `<div class="rl-primary">Showing <b>${shown}</b> of <b>${total}</b></div>`
    : '';

  const sumBtn = document.getElementById('exportSummariesBtn');
  if (sumBtn) {
    const n = Object.keys(state.cache.summaries || {}).length;
    sumBtn.disabled = n === 0;
    sumBtn.textContent = n ? `⬇ Summaries (MD, ${n})` : '⬇ Summaries (MD)';
  }
}

function hasExtractedText(r) {
  if (r.house === 'ls') {
    return !!state.data.manifest?.texts?.ls?.[fileId(r)];
  }
  if (r.house === 'rs') {
    // Any extracted version counts. The detail panel surfaces all
    // available versions; the user can pick. Floor is preferred order
    // but absence of Floor doesn't disqualify the record.
    return rsAvailableVersions(r).length > 0;
  }
  return false;
}
function hasSummary(r) {
  return !!state.cache.summaries[reportKey(r)];
}

function renderList() {
  const list = document.getElementById('reportsList');
  if (!list) return;
  if (!state.filtered.length) {
    list.innerHTML = `<div class="empty-state"><h3>No debates match</h3><p>Try clearing filters.</p></div>`;
    return;
  }
  const slice = state.filtered.slice(0, 200);
  const rawQ = state.filters.search.trim();
  const parsedQ = rawQ ? parseQuery(rawQ) : null;
  list.innerHTML = slice.map(r => {
    const titleHTML = parsedQ ? highlightMatches(r.title || '(untitled)', parsedQ)
                              : escapeHtml(r.title || '(untitled)');
    const house    = HOUSES[r.house] || { short: '??' };
    const housePill = HOUSE_PILL_CLASS[r.house] || 'L';
    const dateStr  = r.debate_date || r.date || '—';
    const sublineParts = [];
    if (r.house === 'ls') {
      sublineParts.push(`LS${r.lok_sabha} · S${r.session}`);
      const m = memberLine(r);
      if (m) sublineParts.push(m);
      if (r.debate_type_desc) sublineParts.push(r.debate_type_desc);
    } else {
      sublineParts.push(`Session ${r.session}`);
    }
    const subline = sublineParts.map(escapeHtml).join(' · ');
    return `
      <div class="report-row" data-key="${escapeHtml(reportKey(r))}">
        <div>
          <div class="report-title">${titleHTML}</div>
          <div class="report-meta">${subline}</div>
        </div>
        <span class="house-pill house-${housePill}" title="${escapeHtml(house.long || '')}">${escapeHtml(house.short)}</span>
        <span class="report-meta">${escapeHtml(dateStr)}</span>
        <span class="text-status ${hasSummary(r) ? 'summary' : (hasExtractedText(r) ? 'ok' : '')}">
          ${hasSummary(r) ? 'summary' : (hasExtractedText(r) ? 'text' : 'metadata')}
        </span>
      </div>
    `;
  }).join('');
  if (state.filtered.length > 200) {
    list.insertAdjacentHTML('beforeend',
      `<div class="empty-state" style="padding:18px"><p>Showing first 200 of ${state.filtered.length} matches — refine filters to narrow further.</p></div>`);
  }
}

function renderHeaderStats() {
  const el = document.getElementById('headerStats');
  if (!el) return;
  const total = getAllReports().length;
  el.innerHTML = `<span><b>${total}</b> debates</span>`;
}

function populateFilters() {
  const reports = getAllReports();
  const lsSet = new Set();
  const sessionSet = new Set();
  const typeMap = new Map();   // debate_type → debate_type_desc
  const yearSet = new Set();
  for (const r of reports) {
    if (r.lok_sabha != null) lsSet.add(r.lok_sabha);
    if (r.session != null) sessionSet.add(r.session);
    if (r.debate_type != null && r.debate_type_desc) {
      typeMap.set(r.debate_type, r.debate_type_desc);
    }
    if (r._year) yearSet.add(r._year);
  }

  const houseSel = document.getElementById('filterHouse');
  if (houseSel) {
    // Only populate houses that actually have records (in phase A, just LS).
    const housesWithData = Object.keys(HOUSES).filter(
      h => Array.isArray(state.data.reports[h]) && state.data.reports[h].length);
    houseSel.innerHTML = '<option value="">All houses</option>' +
      housesWithData.map(h => `<option value="${h}">${escapeHtml(HOUSES[h].long)}</option>`).join('');
  }
  const lsSel = document.getElementById('filterLokSabha');
  if (lsSel) {
    lsSel.innerHTML = '<option value="">All LS terms</option>' +
      [...lsSet].sort((a, b) => b - a).map(v => `<option value="${v}">${v}th Lok Sabha</option>`).join('');
  }
  const sessSel = document.getElementById('filterSession');
  if (sessSel) {
    sessSel.innerHTML = '<option value="">All sessions</option>' +
      [...sessionSet].sort((a, b) => b - a).map(v => `<option value="${v}">Session ${v}</option>`).join('');
  }
  const typeSel = document.getElementById('filterDebateType');
  if (typeSel) {
    const types = [...typeMap.entries()].sort((a, b) => a[1].localeCompare(b[1]));
    typeSel.innerHTML = '<option value="">All types</option>' +
      types.map(([code, desc]) => `<option value="${code}">${escapeHtml(desc)}</option>`).join('');
  }
  const yearSel = document.getElementById('filterYear');
  if (yearSel) {
    yearSel.innerHTML = '<option value="">All years</option>' +
      [...yearSet].sort((a, b) => b - a).map(v => `<option value="${v}">${v}</option>`).join('');
  }

  if (houseSel) houseSel.value = state.filters.house       || '';
  if (lsSel)    lsSel.value    = state.filters.lok_sabha   || '';
  if (sessSel)  sessSel.value  = state.filters.session     || '';
  if (typeSel)  typeSel.value  = state.filters.debate_type || '';
  if (yearSel)  yearSel.value  = state.filters.year        || '';
}

// ── Report dialog ───────────────────────────────────────────────────────────

function openReportByKey(key) {
  const all = getAllReports();
  const r = all.find(x => reportKey(x) === key);
  if (!r) return;
  if (_deps.ai.streaming() && state.streamingContext?.reportKey !== key) {
    _deps.ai.stop();
    state.streamingContext = null;
  }
  state.selectedReport = r;
  state.dialogChat = state.cache.chats[key] ? [...state.cache.chats[key]] : [];
  // RS records: default to whichever version is available, preferring Floor.
  // LS records: ignored.
  if (r.house === 'rs') {
    const avail = rsAvailableVersions(r);
    state.rsSelectedVersion = avail[0] || 'floor';
  } else {
    state.rsSelectedVersion = 'floor';
  }
  document.getElementById('reportTitle').textContent = r.title || '(untitled)';
  renderDetailsTab(r);
  switchReportTab('details');
  document.getElementById('reportModal').classList.add('open');
}

function renderDetailsTab(r) {
  const house = HOUSES[r.house] || { long: '?' };
  // Reconstruct upstream view URL — sansad.in's view-debate route.
  // The PAGE uses lowercased/abbreviated params (?ls=&session=&dbslno=),
  // distinct from the API which uses ?loksabha=&sessionNumber=&dbSlNo=.
  // Caught after first ship when source links returned "Invalid arguments".
  const upstreamUrl = r.house === 'ls'
    ? `https://sansad.in/ls/debates/view-debate?ls=${r.lok_sabha}&session=${r.session}&dbslno=${r.db_slno}`
    : `https://sansad.in/rs/debates/verbatim`;

  let membersHTML = '';
  if (r.house === 'ls' && r.members?.length) {
    membersHTML = `<dt>Member${r.members.length === 1 ? '' : 's'}</dt><dd>` +
      r.members.map(m => escapeHtml(m.mp_name)).join('; ') + `</dd>`;
  }
  let typeHTML = '';
  if (r.house === 'ls' && r.debate_type_desc) {
    typeHTML = `<dt>Type</dt><dd>${escapeHtml(r.debate_type_desc)}</dd>`;
  }

  document.getElementById('detailsTab').innerHTML = `
    <dl class="meta-grid">
      <dt>Title</dt><dd>${escapeHtml(r.title || '—')}</dd>
      <dt>House</dt><dd>${escapeHtml(house.long)}</dd>
      ${r.house === 'ls' ? `<dt>Lok Sabha</dt><dd>${escapeHtml(String(r.lok_sabha))}th</dd>` : ''}
      <dt>Session</dt><dd>${escapeHtml(String(r.session))}</dd>
      <dt>Date</dt><dd>${escapeHtml(r.debate_date || r.date || '—')}</dd>
      ${typeHTML}
      ${membersHTML}
      ${r.keywords?.length ? `<dt>Keywords</dt><dd>${r.keywords.map(escapeHtml).join(', ')}</dd>` : ''}
      <dt>Source</dt><dd><a href="${escapeHtml(upstreamUrl)}" target="_blank" rel="noopener">sansad.in</a></dd>
    </dl>
    <p style="margin-top:14px; font-size:0.82rem; color:var(--muted)">
      ${hasExtractedText(r)
        ? 'Debate text has been extracted by the mirror — see the "Full text" tab or generate an AI summary.'
        : 'Debate text has not yet been extracted by the mirror. The 12×/day Action picks records up incrementally — check back, or follow the source link.'}
    </p>
  `;
}

// Hindi-content detector. ~30%+ of LS speeches are delivered in Hindi
// (sometimes mixed with English chair-interjections). We mirror them
// verbatim — fidelity, not translation — but surface a small nudge so
// users know the Summary / Ask tabs can produce English via their
// configured AI. See plan/debates-recon-001.md §"Decisions" + the
// 2026-05-11 conversation that introduced this.
function _devanagariRatio(text) {
  if (!text) return 0;
  let hindi = 0, latin = 0;
  for (let i = 0; i < text.length; i++) {
    const c = text.charCodeAt(i);
    if (c >= 0x0900 && c <= 0x097F) hindi++;
    else if ((c >= 0x41 && c <= 0x5A) || (c >= 0x61 && c <= 0x7A)) latin++;
  }
  const total = hindi + latin;
  return total === 0 ? 0 : hindi / total;
}

// Version-label map for the RS picker.
const RS_VERSION_LABELS = {
  floor:   { short: 'Floor',        long: 'Floor (canonical, mixed-language as delivered)' },
  english: { short: 'English',      long: 'English version (upstream translation)' },
  part1:   { short: 'Part-1 (Q&A)', long: 'Part-1: Questions and Answers' },
};

async function loadTextTab() {
  const r = state.selectedReport;
  const tab = document.getElementById('textTab');
  if (!r) { tab.innerHTML = ''; return; }
  if (!hasExtractedText(r)) {
    tab.innerHTML = `<p>Debate text hasn't been extracted yet. Open the source link from the Details tab.</p>`;
    return;
  }
  tab.innerHTML = `<p style="color:var(--muted)">Loading…</p>`;

  // RS records: render a small version picker above the body. LS
  // records have only one body, so no picker.
  let pickerHTML = '';
  let version = 'floor';
  if (r.house === 'rs') {
    const avail = rsAvailableVersions(r);
    if (!avail.includes(state.rsSelectedVersion)) {
      state.rsSelectedVersion = avail[0] || 'floor';
    }
    version = state.rsSelectedVersion;
    if (avail.length > 1) {
      const buttons = avail.map(v => {
        const lbl = RS_VERSION_LABELS[v] || { short: v, long: v };
        const active = v === version ? ' active' : '';
        return `<button class="version-pick${active}" data-version="${v}" title="${escapeHtml(lbl.long)}" style="padding:4px 10px; margin-right:6px; border-radius:4px; border:1px solid var(--border); background:${v === version ? 'var(--accent-bg)' : 'transparent'}; color:${v === version ? 'var(--accent)' : 'var(--text)'}; cursor:pointer; font-size:0.85rem">${escapeHtml(lbl.short)}</button>`;
      }).join('');
      pickerHTML = `<div class="version-picker" style="margin-bottom:12px; font-size:0.86rem; color:var(--muted)">
        <span style="margin-right:8px">Version:</span>${buttons}
      </div>`;
    }
  }

  const text = await fetchReportText(r, version);
  if (!text) { tab.innerHTML = pickerHTML + `<p>Could not load the extracted text for this version.</p>`; return; }

  // Surface a hint when the debate is meaningfully Hindi. Single
  // threshold at 30% — below that the speech is mostly English (with
  // occasional Hindi quote / phrase, which doesn't need translation
  // signposting).
  const hr = _devanagariRatio(text);
  let hint = '';
  if (hr >= 0.30) {
    const label = hr >= 0.70 ? 'delivered primarily in Hindi'
                              : 'delivered in Hindi and English';
    hint = `<div class="lang-hint" style="background:var(--info-bg); color:var(--text); padding:10px 14px; border-radius:6px; margin-bottom:12px; font-size:0.86rem; border-left:3px solid var(--navy)">
      <b>हिन्दी / Hindi:</b> this debate was ${escapeHtml(label)} — preserved here in the original.
      For an English summary or to ask questions in English, switch to the
      <b>Summary</b> or <b>Ask</b> tab.
    </div>`;
  }
  tab.innerHTML = pickerHTML + hint + `<pre>${escapeHtml(text)}</pre>`;

  // Wire the version-picker buttons. Re-render the tab on switch.
  if (r.house === 'rs') {
    tab.querySelectorAll('.version-pick').forEach(btn => {
      btn.addEventListener('click', () => {
        state.rsSelectedVersion = btn.dataset.version;
        loadTextTab();
      });
    });
  }
  renderList();
}

function switchReportTab(name) {
  // Multi-corpus guard — see CONV.md "Multi-corpus shared-DOM guard".
  if (_deps.activeCorpus?.() !== 'debates') return;
  document.querySelectorAll('#reportModal .tab-btn').forEach(b => b.classList.toggle('active', b.dataset.tab === name));
  document.querySelectorAll('#reportModal .tab-pane').forEach(p => p.classList.remove('active'));
  document.getElementById(name + 'Tab').classList.add('active');
  if (name === 'text')    loadTextTab();
  if (name === 'summary') renderSummaryTab();
  if (name === 'chat')    renderChatTab();
}

function renderSummaryTab() {
  const tab = document.getElementById('summaryTab');
  const r = state.selectedReport;
  if (!r) { tab.innerHTML = ''; return; }
  if (!_deps.ai.isUsable()) {
    tab.innerHTML = _deps.ai.notReadyHTML();
    _deps.ai.bindNotReadyCTA(tab);
    return;
  }
  const key = reportKey(r);
  const cached = state.cache.summaries[key];
  const isStreaming = state.streamingContext?.reportKey === key
                  &&  state.streamingContext?.tab === 'summary';

  if (isStreaming) {
    tab.innerHTML = `
      <div class="summary-actions">
        <span class="label">Generating summary… (streams in below)</span>
        <button class="ghost sm" id="stopSummaryBtn">Stop</button>
      </div>
      <div class="summary-box" id="summaryBox">${escapeHtml(cached || '')}</div>
    `;
    document.getElementById('stopSummaryBtn').addEventListener('click', () => {
      _deps.ai.stop();
      state.streamingContext = null;
    });
    return;
  }

  tab.innerHTML = `
    <div class="summary-actions">
      <span class="label">Generate a plain-English summary using your configured AI:</span>
      <button class="primary" id="generateSummaryBtn">${cached ? 'Regenerate' : 'Generate'}</button>
      <button class="ghost sm" id="copySummaryBtn" ${cached ? '' : 'style="display:none"'}>Copy</button>
    </div>
    <div class="summary-box" id="summaryBox">${cached ? escapeHtml(cached) : 'No summary yet.'}</div>
  `;
  document.getElementById('generateSummaryBtn').addEventListener('click', generateSummary);
  document.getElementById('copySummaryBtn').addEventListener('click', () => {
    navigator.clipboard.writeText(document.getElementById('summaryBox').textContent || '');
    _deps.ui.toast('Copied');
  });
}

function renderChatTab() {
  const tab = document.getElementById('chatTab');
  const r = state.selectedReport;
  if (!r) { tab.innerHTML = ''; return; }
  if (!_deps.ai.isUsable()) {
    tab.innerHTML = _deps.ai.notReadyHTML();
    _deps.ai.bindNotReadyCTA(tab);
    return;
  }
  const key = reportKey(r);
  const isStreaming = state.streamingContext?.reportKey === key
                  &&  state.streamingContext?.tab === 'chat';

  const messages = state.dialogChat.length
    ? state.dialogChat
    : [{ role: 'system', content: 'Ask anything about this debate intervention. Your question + the debate text are sent to the AI you configured.' }];

  const threadHTML = messages.map(m => {
    const cls = `chat-msg ${m.role}${m.error ? ' error' : ''}`;
    return `<div class="${cls}">${escapeHtml(m.content)}</div>`;
  }).join('');

  const searchOn = _deps.search.isConfigured();
  tab.innerHTML = `
    <div class="chat-thread" id="chatThread">${threadHTML}</div>
    <div class="chat-input-row">
      <textarea id="chatInput" rows="2" placeholder="Ask a question about this debate..." ${isStreaming ? 'disabled' : ''}></textarea>
      ${searchOn ? `<button class="ghost sm" id="chatSearchSendBtn" title="Search the web AND Send" ${isStreaming ? 'disabled' : ''}>&#127760;</button>` : ''}
      <button class="primary" id="chatSendBtn" ${isStreaming ? 'disabled' : ''}>Send</button>
      <button class="ghost sm" id="chatStopBtn" ${isStreaming ? '' : 'style="display:none"'}>Stop</button>
    </div>
  `;
  document.getElementById('chatSendBtn').addEventListener('click', () => chatSend({}));
  if (searchOn) document.getElementById('chatSearchSendBtn').addEventListener('click', () => chatSend({ withSearch: true }));
  document.getElementById('chatStopBtn').addEventListener('click', () => {
    _deps.ai.stop();
    state.streamingContext = null;
  });
  document.getElementById('chatInput').addEventListener('keydown', e => {
    if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); chatSend({}); }
  });
  const t = document.getElementById('chatThread');
  if (t) t.scrollTop = t.scrollHeight;
}

function _truncateForContext(text) {
  const limit = _deps.ai.mode() === 'local' ? 12000 : 60000;
  if (text.length <= limit) return text;
  return text.slice(0, limit) + '\n\n[...truncated for context window...]';
}

async function generateSummary() {
  const r = state.selectedReport;
  if (!r) return;
  // For RS records, default Summary / Ask to operate on whichever
  // version is currently displayed (state.rsSelectedVersion). LS
  // records ignore the version arg.
  const text = await fetchReportText(r, state.rsSelectedVersion);
  if (!text) {
    _deps.ui.toast('Debate text not available — extract pending');
    return;
  }
  const key = reportKey(r);
  const prompt = SUMMARY_PROMPT.replace('{TEXT}', _truncateForContext(text));
  const messages = [
    { role: 'system', content: 'You are a careful, accurate summariser of parliamentary debate transcripts.' },
    { role: 'user',   content: prompt },
  ];
  const previousCached = state.cache.summaries[key] || '';
  state.streamingContext = { reportKey: key, tab: 'summary' };
  renderSummaryTab();
  try {
    const result = await streamWithPersistence({
      generate: _deps.ai.generate,
      messages,
      onText: (full) => {
        if (state.streamingContext?.reportKey === key) {
          const box = document.getElementById('summaryBox');
          if (box) box.textContent = full;
        }
      },
    });
    if (result.ok) {
      state.cache.summaries[key] = result.text;
      idbPut('summaries', key, result.text).catch(() => {});
      if (_deps.disk?.saveAi?.() && _deps.disk?.isConnected?.()) {
        _deps.disk.write('debates', `ai/${r.house}/${fileId(r)}.summary.md`, result.text).catch(() => {});
      }
    } else {
      state.cache.summaries[key] = previousCached;
      _deps.ui.toast('Summary generation failed: ' + result.error.message);
    }
  } finally {
    state.streamingContext = null;
    renderSummaryTab();
    renderList();
  }
}

async function chatSend(opts) {
  opts = opts || {};
  const r = state.selectedReport;
  if (!r) return;
  const input = document.getElementById('chatInput');
  const q = input.value.trim();
  if (!q) return;
  if (_deps.ai.streaming()) { _deps.ui.toast('Already responding…'); return; }
  // For RS records, default Summary / Ask to operate on whichever
  // version is currently displayed (state.rsSelectedVersion). LS
  // records ignore the version arg.
  const text = await fetchReportText(r, state.rsSelectedVersion);
  if (!text) { _deps.ui.toast('Debate text not available'); return; }

  const k = reportKey(r);
  state.dialogChat.push({ role: 'user', content: q });
  try {
    let searchResults = null;
    if (opts.withSearch) {
      if (!_deps.search.isConfigured()) {
        state.dialogChat.push({ role: 'system', content: 'Web search not configured. Open Settings → Web search to add a provider.' });
        input.value = '';
        renderChatTab();
        return;
      }
      state.dialogChat.push({ role: 'system', content: `Searching the web for "${q}"…` });
      renderChatTab();
      try {
        searchResults = await _deps.search.run(q);
        const resultLine = searchResults.length
          ? `Found ${searchResults.length} result${searchResults.length === 1 ? '' : 's'}: ${searchResults.map(x => x.title).slice(0, 3).join(' · ')}${searchResults.length > 3 ? '…' : ''}`
          : 'No web results.';
        state.dialogChat[state.dialogChat.length - 1] = { role: 'system', content: resultLine };
      } catch (e) {
        state.dialogChat[state.dialogChat.length - 1] = { role: 'system', content: 'Search failed: ' + e.message };
        searchResults = null;
      }
    }
    state.dialogChat.push({ role: 'assistant', content: '' });
    state.streamingContext = { reportKey: reportKey(r), tab: 'chat' };
    input.value = '';
    renderChatTab();
    const summary = state.cache.summaries[reportKey(r)];
    const userPrompt = buildAskPrompt({
      summary: summary || null,
      text: _truncateForContext(text),
      searchResults,
      question: q,
    });
    const messages = [
      { role: 'system', content: 'You answer questions about parliamentary debate interventions. Use only the supplied material. If the answer is not present, say so.' },
      { role: 'user',   content: userPrompt },
    ];
    const result = await streamWithPersistence({
      generate: _deps.ai.generate,
      messages,
      onText: (full) => {
        const last = state.dialogChat[state.dialogChat.length - 1];
        last.content = full;
        const lastEl = document.querySelector('#chatThread .chat-msg.assistant:last-child');
        if (lastEl) {
          lastEl.textContent = full;
          const t = document.getElementById('chatThread');
          if (t) t.scrollTop = t.scrollHeight;
        }
      },
    });
    const last = state.dialogChat[state.dialogChat.length - 1];
    if (result.ok) {
      last.content = result.text;
    } else {
      last.error = true;
      last.content = 'Error: ' + result.error.message;
    }
  } finally {
    state.streamingContext = null;
    renderChatTab();
    state.cache.chats[k] = [...state.dialogChat];
    idbPut('chats', k, state.dialogChat).catch(() => {});
    if (_deps.disk?.saveAi?.() && _deps.disk?.isConnected?.()) {
      _deps.disk.write('debates', `ai/${r.house}/${fileId(r)}.chat.json`, JSON.stringify(state.dialogChat, null, 2)).catch(() => {});
    }
  }
}

// ── Export ──────────────────────────────────────────────────────────────────

function _csvCell(v) {
  if (v == null) return '';
  const s = String(v);
  if (/[",\n\r]/.test(s)) return '"' + s.replace(/"/g, '""') + '"';
  return s;
}

function _downloadBlob(filename, mime, content) {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url; a.download = filename;
  document.body.appendChild(a); a.click();
  setTimeout(() => { URL.revokeObjectURL(url); a.remove(); }, 100);
}

function _ts() {
  const d = new Date();
  const pad = n => String(n).padStart(2, '0');
  return `${d.getFullYear()}${pad(d.getMonth()+1)}${pad(d.getDate())}-${pad(d.getHours())}${pad(d.getMinutes())}`;
}

function exportMetadataCSV() {
  const rows = state.filtered;
  if (!rows.length) { _deps.ui.toast('No debates to export'); return; }
  const headers = ['house', 'lok_sabha', 'session', 'db_slno', 'date',
    'debate_type_desc', 'title', 'members', 'has_text', 'has_summary'];
  const lines = [headers.join(',')];
  for (const r of rows) {
    lines.push([
      r.house, r.lok_sabha, r.session, r.db_slno,
      r.debate_date || r.date,
      r.debate_type_desc, r.title,
      (r.members || []).map(m => m.mp_name).join('; '),
      hasExtractedText(r) ? 'yes' : 'no',
      hasSummary(r) ? 'yes' : 'no',
    ].map(_csvCell).join(','));
  }
  _downloadBlob(`sansadsaar-debates-metadata-${_ts()}.csv`, 'text/csv', lines.join('\n') + '\n');
  _deps.ui.toast(`Exported ${rows.length} debates`);
}

function exportSummariesMD() {
  const all = getAllReports();
  const out = [];
  out.push(`# SansadSaar — Debate summaries`);
  out.push('');
  out.push(`Exported ${new Date().toLocaleString('en-IN')}. Source: <https://sansadsaar.naklitechie.com>.`);
  out.push('');
  let n = 0;
  for (const r of all) {
    const key = reportKey(r);
    const summary = state.cache.summaries[key];
    if (!summary) continue;
    n++;
    out.push('---');
    out.push('');
    const house = HOUSES[r.house] || { long: r.house };
    out.push(`## ${house.long} — ${r.title || '(untitled)'}`);
    out.push('');
    const meta = [
      r.house === 'ls' ? `LS${r.lok_sabha} · S${r.session}` : `Session ${r.session}`,
      r.debate_date || r.date,
      r.debate_type_desc,
      memberLine(r),
    ].filter(Boolean).join(' · ');
    if (meta) out.push(`*${meta}*`);
    out.push('');
    out.push(summary);
    out.push('');
  }
  if (!n) { _deps.ui.toast('No debate summaries cached yet'); return; }
  _downloadBlob(`sansadsaar-debates-summaries-${_ts()}.md`, 'text/markdown', out.join('\n'));
  _deps.ui.toast(`Exported ${n} summaries`);
}

// ── IDB hydration ──────────────────────────────────────────────────────────

const _matchDebatesKey = (k) => k.startsWith('debates|');

async function loadCachedSummaries() {
  // Caller gates renderList() on !silent — see drsc/index.js loadCachedSummaries
  // for rationale (silent cross-corpus preloads must not touch visible DOM).
  await hydrateFromIDB({ store: 'summaries', target: state.cache.summaries, matches: _matchDebatesKey });
}
async function loadCachedChats() {
  await hydrateFromIDB({ store: 'chats', target: state.cache.chats, matches: _matchDebatesKey });
}
async function loadCachedTexts() {
  const { added } = await hydrateFromIDB({ store: 'texts', target: state.cache.text, matches: _matchDebatesKey });
  return added;
}

// ── Filter row + handlers ──────────────────────────────────────────────────

function renderFilterRow() {
  const container = document.getElementById('filtersContainer');
  if (!container) return;
  container.innerHTML = `
    <input type="search" id="filterSearch" placeholder="Search debates..." autocomplete="off">
    <select id="filterHouse"><option value="">All houses</option></select>
    <select id="filterLokSabha"><option value="">All LS terms</option></select>
    <select id="filterSession"><option value="">All sessions</option></select>
    <select id="filterDebateType"><option value="">All types</option></select>
    <select id="filterYear"><option value="">All years</option></select>
    <select id="filterSort">
      <option value="newest">Newest first</option>
      <option value="oldest">Oldest first</option>
      <option value="type">By debate type</option>
      <option value="house">By house</option>
    </select>
    <button class="ghost sm" id="resetFiltersBtn" title="Reset filters">&times;</button>
  `;
  document.getElementById('filterSearch').value = state.filters.search || '';
  document.getElementById('filterSort').value   = state.filters.sort   || 'newest';
}

function attachHandlers() {
  const debouncedSearch = debounce(() => { state.filters.search = document.getElementById('filterSearch').value; applyFilters(); }, 200);
  document.getElementById('filterSearch').addEventListener('input', debouncedSearch);
  document.getElementById('filterHouse').addEventListener('change',      e => { state.filters.house       = e.target.value; applyFilters(); });
  document.getElementById('filterLokSabha').addEventListener('change',   e => { state.filters.lok_sabha   = e.target.value; applyFilters(); });
  document.getElementById('filterSession').addEventListener('change',    e => { state.filters.session     = e.target.value; applyFilters(); });
  document.getElementById('filterDebateType').addEventListener('change', e => { state.filters.debate_type = e.target.value; applyFilters(); });
  document.getElementById('filterYear').addEventListener('change',       e => { state.filters.year        = e.target.value; applyFilters(); });
  document.getElementById('filterSort').addEventListener('change',       e => { state.filters.sort        = e.target.value; applyFilters(); });
  document.getElementById('resetFiltersBtn').addEventListener('click', () => {
    state.filters = { search: '', house: '', lok_sabha: '', session: '', debate_type: '', year: '', sort: 'newest' };
    document.getElementById('filterSearch').value      = '';
    document.getElementById('filterHouse').value       = '';
    document.getElementById('filterLokSabha').value    = '';
    document.getElementById('filterSession').value     = '';
    document.getElementById('filterDebateType').value  = '';
    document.getElementById('filterYear').value        = '';
    document.getElementById('filterSort').value        = 'newest';
    applyFilters();
  });

  document.getElementById('reportsList').addEventListener('click', e => {
    const row = e.target.closest('.report-row');
    if (row) openReportByKey(row.dataset.key);
  });

  document.querySelectorAll('#reportModal .tab-btn').forEach(b => {
    if (b.dataset._debatesWired) return;
    b.dataset._debatesWired = '1';
    b.addEventListener('click', () => switchReportTab(b.dataset.tab));
  });
  const closeBtn = document.getElementById('reportCloseBtn');
  if (closeBtn && !closeBtn.dataset._debatesWired) {
    closeBtn.dataset._debatesWired = '1';
    closeBtn.addEventListener('click', () => _deps.ui.closeModal('reportModal'));
  }

  const exportMeta = document.getElementById('exportMetaBtn');
  const exportSum  = document.getElementById('exportSummariesBtn');
  if (exportMeta) exportMeta.onclick = exportMetadataCSV;
  if (exportSum)  exportSum.onclick  = exportSummariesMD;
}

// ── Activation / lifecycle ──────────────────────────────────────────────────

async function activate(deps, { silent = false } = {}) {
  _deps = deps;

  if (!silent) {
    renderFilterRow();
    attachHandlers();
  }

  if (!_activated) {
    _activated = true;

    const ok = await fetchData();
    if (!ok) return false;

    if (!silent) {
      populateFilters();
      renderHeaderStats();
      applyFilters();
    }

    loadCachedSummaries().then(() => { if (!silent) renderList(); });
    loadCachedChats();
    loadCachedTexts().then((n) => {
      if (n && !silent) {
        renderList();
        renderResultsLine();
      }
    });
  } else if (!silent) {
    populateFilters();
    renderHeaderStats();
    applyFilters();
  }

  return true;
}

function refreshAIDependentTabs() {
  if (!state.selectedReport) return;
  const sumActive  = document.getElementById('summaryTab')?.classList.contains('active');
  const chatActive = document.getElementById('chatTab')?.classList.contains('active');
  if (sumActive)  renderSummaryTab();
  if (chatActive) renderChatTab();
}

// ── Settings section ───────────────────────────────────────────────────────

function renderSettingsSection(container) {
  const meta = state.data.meta;
  container.innerHTML = `
    <div class="settings-section">
      <h3>Data (Debates)</h3>
      <p id="debatesDataInfo">${meta
        ? `${_deps.ui.stalenessIndicatorHTML('debates', meta)} · ${escapeHtml(String(meta.total_records))} records total · LSes ${escapeHtml((meta.lok_sabhas || []).join(', '))}`
        : `Source: ${escapeHtml(_deps?.config?.dataBaseUrl || '')}debates/`}</p>
      <button class="sm" id="debatesRefreshDataBtn">Refresh from mirror</button>
    </div>
  `;
  _deps.ui.bindStalenessIndicators(container);

  document.getElementById('debatesRefreshDataBtn').addEventListener('click', async () => {
    _deps.ui.toast('Refreshing debates…');
    await fetchData(true);
    populateFilters();
    renderHeaderStats();
    applyFilters();
    _deps.broadcast('debates:data-refreshed');
    renderSettingsSection(container);
    _deps.ui.toast('Debates data refreshed');
  });
}

function applySettingsFromUI() { /* no debates-specific settings */ }

// ── Status (per-corpus pill) ───────────────────────────────────────────────

async function fetchStatus() {
  const meta = state.data.meta;
  if (!meta) return { lastUpdate: null, items: getAllReports().length, error: null };
  return {
    lastUpdate: meta.generated_at || null,
    items: meta.total_records || getAllReports().length,
    error: null,
  };
}

// ── JS API surface ─────────────────────────────────────────────────────────

const api = {
  list({ house, lok_sabha, session, debate_type, year } = {}) {
    return getAllReports().filter(r => {
      if (house && r.house !== house) return false;
      if (lok_sabha != null && String(r.lok_sabha) !== String(lok_sabha)) return false;
      if (session != null && String(r.session) !== String(session)) return false;
      if (debate_type != null && String(r.debate_type) !== String(debate_type)) return false;
      if (year != null && String(r._year) !== String(year)) return false;
      return true;
    });
  },
  get(key) {
    return getAllReports().find(r => reportKey(r) === key) || null;
  },
  // Title-only search. The `deep`/`any` options are accepted for API
  // uniformity with other corpora but no-op here — debates is title-only
  // in SansadSaar (the richer per-MP experience is moving to
  // indiavotes.com/netas).
  async search(query, opts = {}) { // eslint-disable-line no-unused-vars
    const parsedQ = parseQuery(query);
    if (!parsedQ.tokens.length && !parsedQ.phrases.length) return getAllReports();
    return getAllReports().filter(r => {
      const titleLower = (r.title || '').toLowerCase();
      return parsedQ.tokens.every(t => titleLower.includes(t))
          && parsedQ.phrases.every(p => titleLower.includes(p));
    });
  },
  open(key) {
    const r = api.get(key);
    if (!r) return false;
    openReportByKey(reportKey(r));
    return true;
  },
  async searchForGlobal(query, { deep = true, limit = 10 } = {}) { // eslint-disable-line no-unused-vars
    const items = await api.search(query);
    const subs = (r) => {
      const parts = [];
      const h = HOUSES[r.house];
      if (h) parts.push(h.short);
      if (r.house === 'ls' && r.lok_sabha) parts.push(`LS${r.lok_sabha}`);
      if (r.session) parts.push(`S${r.session}`);
      if (r.debate_date || r.date) parts.push(r.debate_date || r.date);
      return parts.join(' · ');
    };
    return items.slice(0, limit).map(r => ({
      key:      reportKey(r),
      title:    r.title || '(untitled)',
      subtitle: subs(r),
    }));
  },
  houses: () => Object.keys(HOUSES),
};

// ── Export the corpus contract ─────────────────────────────────────────────

export const DebatesCorpus = {
  id:          'debates',
  label:       'Debates',
  shortLabel:  'Debates',
  macroGroup:  'proceedings',
  primaryUnit: 'debate',

  fetchStatus,
  activate,

  api,
  renderSettingsSection,
  applySettingsFromUI,
  refreshAIDependentTabs,
};
